[package]
name = "salvo-vite-test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
salvo = "0.88.1"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
